services:
  web:
    container_name: qcoordinacion-web
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    ports:
      - 3000:3000